### ISSUE TITLE
Bad Ciphertext : incorrect plaintext length

### ISSUE THREAD

**Issue by grlsdmsugr** [DoubleLabyrinth/how-does-SecureCRT-encrypt-password#11]
I'm getting the following error when I try to decrypt a password using your code, do you have any idea what the issue could be.  The password i'm trying to decrypt is from a Secure CRT session.

S:"Username"=USER1
S:"Monitor Password V2"=03: 
S:"Password V2"=03: ***I tried to decrypt the password that was listed here.***
S:"Login Script V3"=02: 

The error i received from running the script is listed below.
Traceback (most recent call last):
  File "C:\Users\vkari\securecrt_cipher.py", line 266, in <module>
    print(getattr(cipher, operation)(args.PASSWORD, prefix = args.prefix))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vkari\securecrt_cipher.py", line 175, in decrypt
    raise ValueError('Bad ciphertext: incorrect plaintext length.')
ValueError: Bad ciphertext: incorrect plaintext length.

**Comment by BlueNoob** [comment]
Do you have a passphase? If possiable, type your password, I can have a try.

**Comment by HQ222222** [comment]
This situation is that when setting the SecureCRT password, the -p parameter needs to be added during decryption: "dec -2 --prefix 03 -p 'Your password' "
